name: tests

on:
    push:
        branches:   [main]
    pull_request:
        branches:   [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses:   actions/checkout@v2
            -   name:   Install python
                uses:   actions/setup-python@v2
                with:
                    python-version: 3.11
            -   name:   Install dependencies
                run:    |
                    python -m pip install --upgrade pip;
                    pip install -r ./tests/requirements.txt
            -   name: Run black
                run:    |
                    black ./homework_1;
                    black ./homework_2
            -   name: Run tests homework_1
                run:    pytest -vs ./homework_1
            -   name: Run tests homework_2
                run:    pytest -vs ./homework_2