name: tests

on:
    push:
        branches:   [main]
    pull_request:
        branches:   [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses:   actions/checkout@v2
            -   name:   Install python
                uses:   actions/setup-python@v2
                with:
                    python-version: 3.11
            -   name:   Install dependencies
                run:
                    python -m pip install --upgrade pip;
                    pip install -r ./tests/requirements.txt
            -   name:   Run flake8
                run:
                    flake8 ./homework_1/main.py
                    flake8 ./homework_2/main.py
            -   name: Run black
                run:
                    black ./homework_1
                    black ./homework_2
            -   name: Run tests
                run:
                    pytest -vs ./homework_1
                    pytest -vs ./homework_2