name: tests

on:
    push:
        branches:   [main]
    pull_request:
        branches:   [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses:   actions/checkout@v2
            -   name:   Install python
                uses:   actions/setup-python@v2
                with:
                    python-version: 3.11
            -   name:   Install dependencies
                run:
                    python -m pip install --upgrade pip;
                    pip install -r ./tests/requirements.txt
            -   name:   Run flake8
                run:
                    cd ./homework_1  
                    flake8 main.py
            -   name: Run black
                run: black .
            -   name: Run tests
                run:
                    cd ./homework_1 
                    pytest -vs .